# Generated by Django 5.1 on 2025-12-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='invoice_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
