# Generated by Django 5.1 on 2025-10-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(blank=True, default='profile_pics/cat.2.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
