# Generated by Django 5.1 on 2025-12-23 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
        ('store', '0002_delivery_invoice_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='store.delivery'),
        ),
    ]
